name: CI Docker Image

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the App Docker image
        working-directory: ./
        run: docker build . --file Dockerfile --tag chance:$(date +%s)
